spring:
  jackson:
    generator:
      write-bigdecimal-as-plain: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1h
    cache-names: discountPolicies
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: ${MYSQL_USER}
    password: ${MYSQL_SECRET}
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env-variables.local[.properties]

discount:
  admin-token: ${ADMIN_TOKEN}

logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.cache.interceptor: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.jdbc.datasource.DataSourceUtils: DEBUG
    org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator: DEBUG
